export const blacklisted_names = [
    "Dedicated Server",
    "Single Player",
    "TestApp",
    "SDK",
    "DLC",
    "Trailer",
    "Teaser",
    "Steam",
    "Singleplayer",
    "Editor",
    "Expansion",
    "Bonus",
    "Tutorial",
    "Tool",
    "Linux",
    "Demo",
    "(French)",
    "(German)",
    "(Spanish)",
    "(Russian)",
]